### ISSUE TITLE
Strange way to show transaction when approving pool on rskswap.com

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#441]
![photo_2020-08-27_17-18-04](https://user-images.githubusercontent.com/1178856/91490761-599f5800-e889-11ea-80ad-db9c7d174abf.jpg)

**Comment by imstar15** [comment]
duplicate of #436

**Comment by imstar15** [comment]
It's fixed by back-end.

**Comment by bitcoinuser** [comment]
For me, I still see the problem.

**Comment by bitcoinuser** [comment]
Hi @chrisli30 and @imstar15, any idea why on my wallet this was not fixed?

**Comment by imstar15** [comment]
When a new version of the server is deployed, it will be fixed.
@bitcoinuser

**Comment by bitcoinuser** [comment]
> When a new version of the server is deployed, it will be fixed.
> @bitcoinuser

Any idea when will happen?

**Comment by bitcoinuser** [comment]
I think this bug should be reopened until it's fixed to end users. I still see this problem on version 1.3.1.

Thanks.

**Comment by chrisli30** [comment]
Yes I agree

**Comment by imstar15** [comment]
@bitcoinuser We fix it, please check again.

**Comment by bitcoinuser** [comment]
> @bitcoinuser We fix it, please check again.

Yes, fixed. I just don't understand why only show the last two transactions. 

![photo_2020-09-30_13-41-38](https://user-images.githubusercontent.com/1178856/94714571-b37cbd00-0322-11eb-8690-6fb601fe5d0d.jpg)

**Comment by imstar15** [comment]
Ok i will continue to follow up on this issue
@bitcoinuser
